//
//  ImgMacro.h
//  InstaVoice
//
//  Created by Eninov on 14/10/13.
//  Copyright (c) 2013 EninovUser. All rights reserved.
//

#ifndef InstaVoice_ImgMacro_h
#define InstaVoice_ImgMacro_h

//#define IMG_LAUNCH                      @"LaunchImg"
//#define IMG_LAUNCH_568H                 @"LaunchImg-568h@2x"

//#define IMG_CONNECT                     @"connect"
//#define IMG_OFF_BUTTON                  @"off_button"
//#define IMG_ON_BUTTON                   @"on_button"
//#define IMG_VOBOLO_LABEL                 @"blogs_share_grey"
//#define IMG_WHITE_RIGHT                 @"white_right"
//#define IMG_GREYBAR                     @"greybar"
//#define IMG_BACKIMG                     @"backImg"
//#define IMG_DOWN_ARROW                  @"down_arrow"
//#define IMG_MISSEDCALL                  @"missedCallWhite"
//#define IMG_ORAGNE_AUDIO_MSG            @"orange_audio_mag"
//#define IMG_RIGHT_ARR_BLACK             @"right_arr_black"
#define IMG_RIGHT_ARR_GRAY              @"right_arr_gray"
#define IMG_LIKED                       @"liked"
#define IMG_VOBOLO_POST                 @"share-icon-vb"
#define IMG_FWD_GREY_TEXT_IMG           @"fwd_msg"
//#define IMG_FWD_MSG_WHITE_IMG           @"fwd_msg_white"
#define IMG_FWD_WHITE_IMG               @"share-icon-iv"
//#define MENU_SCREEN_LOGO                @"menuscreen_logo"
//#define MENU_BGIMG                      @"bgImg"
//#define MENU_BGIMG_2X                   @"bgImg-568h@2x"
//#define MENU_SCREEN_TRANSPARENT         @"Menuscreen_transparent_header"
//#define IMG_MORE_WHITE                  @"more_white"

//#define IMG_VOBOLO_POST_MSG             @"blogs_share_white"
//#define IMG_GREY_BAR                    @"grey_bar"
//#define IMG_IV_SHARE_ICON               @"instaVoice_share_icon"
//#define IMG_FB_1                        @"facebook_1"
//#define IMG_HEART                       @"heart"
#define IMG_DELETE                      @"delete"
//#define IMG_CALL                      @"call"
//#define IMG_ADDRESS_ICON                @"address_icon"
//#define IMG_ARROW_SPINNER               @"arrow_spinner"
//#define IMG_CHECKED                     @"checked"
//#define IMG_DATE                        @"date"
//#define IMG_FB_WHITE                    @"facebook_white"
//#define IMG_GOOGLE                      @"google"
#define IMG_MALE_PNG                    @"male"
//#define IMG_PENCIL                      @"pencil"
//#define IMG_PROFILE                     @"profile"
//#define IMG_SELECT_ALL_FRND_GREEN       @"select_all_friend_green"
//#define IMG_SELECT_ALL_FRND_GREY        @"select_all_friend_grey"
//#define IMG_SELECT_GREY                 @"select_grey"
//#define IMG_TWITTER_BAR                 @"twitter_bar"
//#define IMG_TWITTER_WHITE               @"twitter_white"
#define IMG_TWITTER_POST                @"share-icon-tw"
//#define IMG_UNCHECKED                   @"unchecked"
//#define IMG_YAHOO                       @"yahoo"

//#define IMG_PLAY_AUDIO                  @"play_audio"
//#define IMG_VOICE                       @"voice"
#define IMG_FB_GREY_POST                @"share-icon-fb"
#define IMG_VB_GREY_POST                @"share-icon-vb" 
#define IMG_TW_GREY_POST                @"share-icon-tw"
#define IMG_IC_FB_M                     @"ic-fb-m"
#define IMG_IC_LOGO_M                   @"ic-logo-m"
#define IMG_IC_EMAIL                    @"email-friends"//"ic-mail"
#define IMG_IC_MOB_GREY                 @"new-mobile-chat"

//#define IMG_FB_BLUE                     @"voice_msg_fb_blue"

//#define IMG_IC_SEARCH_BLUE_M            @"ic-search-blue-m"
//#define IMG_IC_SEARCH_WHITE_M           @"ic-search-white-m"

#define IMG_IC_INVITE_BLUE_M            @"ic-invite-blue-m"
//#define IMG_IC_INVITE_GREY_M            @"ic-invite-grey-m"
//#define IMG_IC_INVITE_WHITE_M           @"ic-invite-white-m"

#define IMG_IC_TICK_GRN_M               @"ic-tick-grn-m"
//#define IMG_IC_TICK_WHITE_M             @"ic-tick-white-m"
#define IMG_IC_TICK_GREY_M              @"ic-tick-grey-m"

//#define IMG_TABBARLEFT                  @"topBarLeft"
//#define IMG_TABBARMID                   @"topBarMid"
//#define IMG_TABBARRIGHT                 @"topBarRight"



//#define IMG_FB_LABEL                    @"facebook_label"
//#define IMG_TW_LABEL                    @"twitter_label"  //Edited by Jatin
//#define IMG_MSG_SENDING                 @"msg_sending"
//#define IMG_AVS_MSG                     @"voicemail"
//#define IMG_AVS_MSG_GREY                @"voicemailGrey"
//#define IMG_DOWNLOAD_ERROR              @"download_error"
//#define IMG_LOADING                     @"loading"
//#define IMG_CANCEL_BTN                  @"cancel_btn"
//#define IMG_SEND_BTN                    @"send_btn"
//#define IMG_DEFAULT_USER                @"default_user"
//#define IMG_SEARCH_TEXT_BG              @"default_text_bg"
//#define IMG_DEFAULT_USER_GRID_PIC       @"default_user_grid_pic"
//#define IMG_ADD_ICON                    @"add_icons"
#define IMG_INSTA_FWD_ICON              @"share-icon-iv"

//#define IMG_CONTACT                     @"Chats_plus_icon"

//#define IMG_ADDFRIEND                   @"addFriend"
//#define IMG_AUDIO_MSG                   @"audio_msg"
//#define IMG_AUDIO_MSG_GRAY              @"audio_msg_gray"
//#define IMG_TEXTMSG_MSG                 @"icon_textmsg_indicator"
//#define IMG_FOR_IMG_MSG                 @"icon_imgmsg_indicator"
#define IMG_BACK                        @"back"
//#define IMG_OPTION_DEFAULT              @"option_default"
//#define IMG_OPTION_BTN                  @"option_btn"
//#define IMG_OPTION_1                    @"option_1"
//#define IMG_OPTION_2                    @"option_2"
//#define IMG_OPTION_3                    @"option_3"
//#define IMG_BACK_VOICE                  @"back_voice"
//#define IMG_BACKBTN                     @"backBtn"
//#define IMG_BOTTOM_BAR_BLUE             @"Bottom_bar_blue"
#define IMG_CONVERSATION                @"conversation"
#define IMG_CONVERSATIONS               @"conversations"
//#define IMG_COUNTRY_BG                  @"country_bg"
//#define IMG_CROSSBLACK                  @"crossBlack"
//#define IMG_CROSSWHITE                  @"crossWhite"
//#define IMG_CLOSE                       @"close"

//#define IMG_FB                          @"facebook"
//#define IMG_FB_LABEL_SPLASH             @"facebook_label_splash" //Edited by Jatin
//#define IMG_FRIENDS                     @"friends"
//#define IMG_HAND                        @"hand"

//#define IMG_CHAT_MSG_ICON               @"MenuChatIcon"
//#define IMG_CHAT_GRP_MSG_ICON           @"groupChatIcon"
//#define IMG_CHAT_MSG_GREY               @"ChatGrey"
//#define IMG_CANCEL                       @"close"
//#define IMG_BLUE                         @"blue"

//#define IMG_LAUNCHER_ICON               @"launcher_icon"
#define IMG_LOADER_BLACK                @"loader_black"
#define IMG_LOADER_BLACK_COUNTER        @"loader_black_counter"
//#define IMG_LOADER_GREEN                @"loader_black"
//#define IMG_LOADER_GREEN_COUNTER        @"loader_black_counter"
//#define IMG_ICON_DEL_OPEN               @"icon_delete_open"

//#define IMG_LOGIN_BTN                   @"login_btn"
//#define IMG_MSG_UNREAD                  @"message_unread"
//#define IMG_MIC_GREEN                   @"mic-green"
//#define IMG_MIC_YELLOW                  @"mic-yellow"
#define IMG_MIC                         @"mic"

#define IMG_NOTES                       @"notes"
//#define IMG_PROFILEIMG                  @"profileImage"
//#define IMG_RECORDING_BAR               @"recoding_bar"
//#define IMG_RED_BAR_TOP1                @"red_bar_top1"
//#define IMG_RIGHT_ARROW                 @"right_arrow"
//#define IMG_SEARCH_TXT_BG               @"search_text_bg.text"
//#define IMG_SEND                        @"ChatSend"
#define IMG_SETTINGS                    @"settings"
#define IMG_SIGN_OUT                    @"sign_out"
//#define IMG_SPLASH                      @""
//#define IMG_ICON_CHAT_DEL               @"icon_chat_delete"
#define IMG_SPEAKER_OFF                 @"speaker_mode"
//#define IMG_BLUETOOTH                   @"bluetooth"
//#define IMG_HEADPHONE                   @"headphone_settings"

//#define IMG_SPEAKER_ON                  @"speaker_on"
//#define IMG_SPEAKING                    @"speaking"
//#define IMG_MENU_ITEM1                  @"menu_item1_bg"
//#define IMG_MENU_ITEM2                  @"menu_item2_bg"
//#define IMG_MENU_ITEM3                  @"menu_item3_bg"
//#define IMG_MENU_ITEM4                  @"menu_item4_bg"
//#define IMG_MENU_ITEM5                  @"menu_item5_bg"
//#define IMG_MENU_ITEM6                  @"menu_item6_bg"

//#define IMG_PROFILE_PIC_FILTER          @"profile_picture_filter_top"
//#define IMG_MENU_BACKGROUNG_IMG         @"menu_logo"
//#define IMG_TEXT_FIELD_PWD              @"Text_field_password"
//#define IMG_TEXT_MSG_ICON               @"text_msg_icon"
#define IMG_TRANSPARENT_STRIPE_READ     @"transparent_stripe_read"
#define IMG_TRANSPARENT_STRIPE_UNREAD   @"transparent_stripe_unread"
//#define IMG_TW_LABEL_SPLASH             @"twitter_label_splash"
#define IMG_USER1                       @"user1"
//#define IMG_USERNAME_FIELD              @"username_field"
//#define IMG_VOBOLO                      @"vobolo"
//#define IMG_VOBOLO_LABEL_SPLASH         @"vobolo_label_splash"
//#define IMG_VOICE_MSG                   @"voice_msg"
#define IMG_WORLD_ICON                  @"world_icon"
//#define IMG_SELECT_GREEN                @"select_green"
//#define IMG_FACEBOOK_LABEL              @"facebook_label"
//#define IMG_TWITTER_LABEL               @"twitter_label"
//#define IMG_FACEBOOK_1                  @"facebook_1"
#define IMG_FACEBOOK_POST               @"share-icon-fb"
//#define IMG_BG_INVITE_CANCEL            @"bg_invite_cancel"
//#define IMG_BG_INVITE_SEND              @"bg_invite_send"
//#define IMG_BG_INVITE_MID               @"bg_invite_mid"
//#define IMG_COUNTRY_TV_BG               @"country_tv_background"
//#define IMG_GREEN_TEXT_READ              @"iv_green_text_read"
//#define IMG_GREY_TEXT_READ               @"iv_grey_text_read"
//#define IMG_GREY_MISSEDCALL_IMG               @"missedCallIncoming"
//#define IMG_BLUE_TEXT_READ               @"iv_blue_text_read"
//CMP NOV-14 #define IMG_ORANGE_TEXT_READ             @"iv_orange_text_read"
//#define IMG_ORANGE_TEXT_READ             @"rec_orange_read"

//#define IMG_GREEN_TEXT_UNREAD              @"iv_green_text_unread"
#define IMG_GREY_TEXT_UNREAD               @"iv_grey_text_unread"
//#define IMG_BLUE_TEXT_UNREAD               @"iv_blue_text_unread"
//#define IMG_ORANGE_TEXT_UNREAD             @"iv_orange_text_unread"


#define IMG_LOADER_BLACK_A              @"loader_black_counter_droped_a"

#define IMG_LOADER_GREEN_PLAYING @"playing_m"
#define IMG_LOADER_GREEN_SPEAKER @"speaker_m"
#define IMG_LOADER_RED_RECORDING @"red_circle_m"

#define IMG_LOADER_BLACK_B              @"loader_black_counter_droped_b"
#define IMG_LOADER_BLACK_C              @"loader_black_counter_droped_c"
#define IMG_LOADER_BLACK_D              @"loader_black_counter_droped_d"
#define IMG_LOADER_BLACK_NOR            @"loader_black_counter_droped_nor"
//#define IMG_IC_MAIL                     @"ic_mail"
//#define IMG_IC_PHONE                    @"ic_phone"

// setting Images
//#define IMG_DISCONNECT_IV               @"disconnect_iv_bg"
#define IMG_UPLOAD                      @"blue_btn"
//#define IMG_RIGHT_ARR_BLUE              @"right_arrow_blue"
//#define IMG_FBCNT_BG                    @"fb_connect"
//#define IMG_TWCNT_BG                    @"twitter_connect"

#define IMG_ON                          @"on"
#define IMG_OFF                         @"off"
#endif
